### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by mroberts1** [Yukuro/goph-to-stylesheet#1]
Hi - just wondering how to run this after downloading the repo. Is it a Go program? I'm using a zsh shell and when I run the convert script on a goph theme I get "command not found".

**Comment by Yukuro** [comment]
This is Go program.
The executable `goph-to-stylesheet` is a renamed version of the main.go build.

So you can use the executable `goph-to-stylesheet` and run it like this
```bash
$cd goph-to-stylesheet
$./goph-to-stylesheet [-t goph_theme] [-i input_file] [-o output_file]
```

You can also use `go build` to create the executable of your choice
```bash
$cd goph-to-stylesheet
$go build ./main.go
$./main [-t goph_theme] [-i input_file] [-o output_file]
```

**Comment by mroberts1** [comment]
I'm sorry, Iam using MacOS with Go installed but am not familiar with using Go.

First, I am using zsh shell (iTerm2): do I need to run bash shell for these commands to work?

In zsh shell I can run goph-to-stylesheet with 'go run goph-to-stylesheet -t ic-green-ppl.sh -i template/shell.scss -o goph.scss'

Here I have ic-green-ppl.sh in the same directory but goph-to-stylesheet cannot find it:

> theme 'ic-green-ppl.sh' not found in goph

goph-to-stylesheet is installed in ~/go/src

I also have gogh directory in the goph-to-stylesheet directory with all themes, but goph-to-stylesheet cannot find the name of the theme that I give.

How can I make goph-to-stylesheet find the gogh theme that I want to convert?

**Comment by Yukuro** [comment]
I haven't tried this script with zsh, but I think it works.

This script fetches [theme.json](https://raw.githubusercontent.com/Mayccoll/Gogh/master/data/themes.json) to get the color information.
The name of the theme must be the same as the name given on [this site](https://mayccoll.github.io/Gogh/).

Thus, it does not need *.sh to run
In this case, the following is the execution you were looking for
```bash
./goph-to-stylesheet -t ICGreenPPL -i template/shell.scss -o goph.scss
```

**Comment by mroberts1** [comment]
Ok it works now, running the command above with 'go run ...'


This is great that it completely opens up all of the Gogh terminal themes - thanks for your help and also for writing the guide!
